# Generated by Django 5.0.1 on 2024-01-23 17:31

import django.utils.timezone
import mdeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Passage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.CharField(blank=True, max_length=50)),
                ('body', mdeditor.fields.MDTextField()),
                ('pid', models.PositiveIntegerField(unique=True)),
                ('abstract', mdeditor.fields.MDTextField(blank=True, null=True)),
                ('abstract_after_changed', models.TextField(blank=True, null=True)),
                ('absimg', models.URLField(blank=True)),
                ('tags', models.ManyToManyField(related_name='passages', to='passage.tag')),
            ],
        ),
    ]
