# Generated by Django 5.0.1 on 2024-01-23 17:31

import mdeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('body', mdeditor.fields.MDTextField()),
                ('body_after_changed', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
